version:
	docker-compose run --rm client /home/version 

dotnet-client:
	docker-compose run --rm dotnet 

client:
	docker-compose run --rm client 

os-release:
	docker-compose run --rm client cat /etc/os-release
